-- MySQL Script generated by MySQL Workbench
-- Sat May  6 18:34:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pogoscanner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pogoscanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pogoscanner` DEFAULT CHARACTER SET utf8 ;
USE `pogoscanner` ;

-- -----------------------------------------------------
-- Table `pogoscanner`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`pokemon` (
  `pokemon_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `french_name` VARCHAR(40) NOT NULL,
  `english_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`pokemon_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`notified_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`notified_person` (
  `notified_person_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `free_user_id` VARCHAR(10) NOT NULL,
  `free_api_key` VARCHAR(20) NOT NULL,
  `email_notify` TINYINT(1) UNSIGNED NOT NULL,
  `free_sms_notify` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`notified_person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`pokemon_move`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`pokemon_move` (
  `pokemon_move_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `french_name` VARCHAR(30) NOT NULL,
  `english_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`pokemon_move_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`pokemon_gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`pokemon_gender` (
  `pokemon_gender_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `french_name` VARCHAR(10) NOT NULL,
  `english_name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pokemon_gender_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`zone` (
  `zone_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `sw_latitude` DECIMAL(12,10) NOT NULL,
  `sw_longitude` DECIMAL(14,11) NOT NULL,
  `ne_latitude` DECIMAL(12,10) NOT NULL,
  `ne_longitude` DECIMAL(14,11) NOT NULL,
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL,
  `lastscan_date` DATETIME NOT NULL,
  `has_returned_data` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`zone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`spawn_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`spawn_point` (
  `spawn_point_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pokemon_id` INT UNSIGNED NOT NULL,
  `encounter_id` VARCHAR(35) NOT NULL,
  `zone_id` INT UNSIGNED NULL,
  `latitude` DECIMAL(12,10) NOT NULL COMMENT 'Between -90 and +90 degrees',
  `longitude` DECIMAL(14,11) NOT NULL COMMENT 'Between -180 and +180 degrees',
  `iv_attack` TINYINT(2) UNSIGNED NULL,
  `iv_defense` TINYINT(2) UNSIGNED NULL,
  `iv_stamina` TINYINT(2) UNSIGNED NULL,
  `spawn_date` DATETIME NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  `pokemon_move_id_1` INT UNSIGNED NULL,
  `pokemon_move_id_2` INT UNSIGNED NULL,
  `pokemon_gender_id` INT UNSIGNED NULL,
  `spawnpoint_id` VARCHAR(15) NOT NULL,
  `is_notification_sent` TINYINT(1) UNSIGNED NOT NULL,
  `date_add` DATETIME NOT NULL,
  `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`spawn_point_id`),
  INDEX `fk_spawn_point_pokemon_idx` (`pokemon_id` ASC),
  INDEX `idx_spawn_point_encounter_id_spawpoint_id` (`encounter_id` ASC, `spawnpoint_id` ASC),
  INDEX `idx_spawn_point_spawnpoint_id` (`spawnpoint_id` ASC),
  INDEX `fk_spawn_point_pokemon_move1_idx` (`pokemon_move_id_1` ASC),
  INDEX `fk_spawn_point_pokemon_move2_idx` (`pokemon_move_id_2` ASC),
  INDEX `fk_spawn_point_pokemon_gender1_idx` (`pokemon_gender_id` ASC),
  INDEX `fk_spawn_point_zone1_idx` (`zone_id` ASC),
  UNIQUE INDEX `idx_spawn_point_encounter_id` (`encounter_id` ASC),
  CONSTRAINT `fk_spawn_point_pokemon_pokemon_id`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `pogoscanner`.`pokemon` (`pokemon_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spawn_point_pokemon_move1_move_id`
    FOREIGN KEY (`pokemon_move_id_1`)
    REFERENCES `pogoscanner`.`pokemon_move` (`pokemon_move_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spawn_point_pokemon_move2_move_id`
    FOREIGN KEY (`pokemon_move_id_2`)
    REFERENCES `pogoscanner`.`pokemon_move` (`pokemon_move_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spawn_point_pokemon_gender_gender_id`
    FOREIGN KEY (`pokemon_gender_id`)
    REFERENCES `pogoscanner`.`pokemon_gender` (`pokemon_gender_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spawn_point_zone_zone_id`
    FOREIGN KEY (`zone_id`)
    REFERENCES `pogoscanner`.`zone` (`zone_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`configuration` (
  `key` VARCHAR(150) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`notifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`notifier` (
  `pokemon_id` INT UNSIGNED NOT NULL,
  `min_iv` FLOAT(4,1) UNSIGNED NOT NULL COMMENT 'Minimal IV rate to send notification',
  `is_disallowed` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Set to 1 if Pokemon should not be notified',
  `is_important` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Set to 1 if notified users should be notiifed by an extra mean (like SMS) for that Pokémon',
  PRIMARY KEY (`pokemon_id`),
  CONSTRAINT `fk_notifier_pokemon_pokemon_id`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `pogoscanner`.`pokemon` (`pokemon_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pogoscanner`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogoscanner`.`server` (
  `server_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `server_address` VARCHAR(80) NOT NULL,
  `is_secure` TINYINT(1) UNSIGNED NOT NULL,
  `scan_request_uri` VARCHAR(100) NOT NULL COMMENT 'URI used to request scan results data.',
  `control_request_uri` VARCHAR(100) NULL COMMENT 'URI eventually used to make a pre-control request (optional for some servers).',
  `is_online` TINYINT(1) UNSIGNED NOT NULL,
  `last_request_date` DATETIME NULL,
  `last_session_params` TEXT NULL,
  PRIMARY KEY (`server_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
