LOAD DATA LOCAL INFILE 'resources/data/pokemon.csv'
INTO TABLE pokemon
CHARACTER SET UTF8
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'resources/data/pokemon_move.csv'
INTO TABLE pokemon_move
CHARACTER SET UTF8
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 ROWS;